In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler , OneHotEncoder 
import tensorflow as tf
import pickle
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 
from tensorflow.keras.callbacks import TensorBoard, EarlyStopping

In [5]:
data = pd.read_csv("Churn_Modelling.csv")

data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
data = data.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [11]:
labelEncoderGenderReg = LabelEncoder()

data["Gender"] = labelEncoderGenderReg.fit_transform(data["Gender"])

data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [12]:
oneHotEncoderGeo = OneHotEncoder()

geoEncoded = oneHotEncoderGeo.fit_transform(data[["Geography"]])

geoEncoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [13]:
oneHotEncoderGeo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [20]:
geoEncodedDf = pd.DataFrame(geoEncoded.toarray(),columns=oneHotEncoderGeo.get_feature_names_out(["Geography"]))

In [21]:
data = pd.concat([data.drop(["Geography"],axis=1),geoEncodedDf],axis=1)

In [24]:
X = data.drop(["EstimatedSalary"],axis=1)
Y = data["EstimatedSalary"]

In [25]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [26]:
scalerReg = StandardScaler()

X_train = scalerReg.fit_transform(X_train)
X_test = scalerReg.fit_transform(X_test)

In [29]:
with open("labelEncoderGenderReg.pkl","wb") as file:
    pickle.dump(labelEncoderGenderReg,file)

with open("OneHotEncoderGeoReg.pkl","wb") as file:
    pickle.dump(oneHotEncoderGeo,file)

with open("scalerReg.pkl","wb") as file:
    pickle.dump(scalerReg,file)

In [42]:
model = Sequential([
    Dense(64,activation="relu",input_shape=(X_train.shape[1],)),
    Dense(32,activation="relu"),
    Dense(1)
])

In [43]:
model.compile(optimizer="adam",loss="mean_absolute_error",metrics=["mae"])

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
import datetime


logsDir = "logs_dir_reg" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorFlowCallBack = TensorBoard(log_dir=logsDir,histogram_freq=1)

In [45]:
earlyStoppingCallBack = EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [46]:
history = model.fit(
    X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,callbacks=[earlyStoppingCallBack,tensorFlowCallBack]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 100366.9297 - mae: 100366.9297 - val_loss: 98478.4609 - val_mae: 98478.4609
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99474.2266 - mae: 99474.2266 - val_loss: 96664.5469 - val_mae: 96664.5469
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96324.9609 - mae: 96324.9609 - val_loss: 92054.0312 - val_mae: 92054.0312
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90237.5391 - mae: 90237.5391 - val_loss: 84578.1328 - val_mae: 84578.1328
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 81603.9219 - mae: 81603.9219 - val_loss: 75246.8047 - val_mae: 75246.8047
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 71931.4141 - mae: 71931.4141 - val_loss: 66135.4219 - val_mae: 66135.4219
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 63178.4961 - mae: 63178.4961 - val_loss: 58820.1602 - val_mae: 58820.1602
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 56866.7461 - mae: 56866.7461 - val_loss: 54198.2930 - val_mae: 54198.2930
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53241.8984 - mae: 53241.8984 - val_loss: 51959.2305 - val_mae: 51959.2305
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51540.3359 - mae: 51540.3359 - val_loss: 51184.7539 - val_mae: 51184.7539
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50860.2852 - mae: 50860.2852 - val_loss: 50941.4297 - val_mae: 50941.4297
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50617.1797 - mae: 50617.1797 - val_loss: 50854.8203 - val_mae: 50854.8203
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50471.3672 - mae: 50471.3672 - val_loss: 50791.1914 - val_mae: 50791.1914
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50368.4141 - mae: 50368.4141 - val_loss: 50750.0703 - val_mae: 50750.0703
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50287.2070 - mae: 50287.2070 - val_loss: 50695.7109 - val_mae: 50695.7109
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50222.4805 - mae: 50222.4805 - val_loss: 50657.4258 - val_mae: 50657.4258
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50161.7852 - mae: 50161.7852 - val_loss: 50605.7812 - val_mae: 50605.7812
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50108.1758 - mae: 50108.1758 - val_loss: 50573.8672 - val_mae: 50573.8672
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50062.6016 - mae: 50062.6016 - val_loss: 50542.4883 - val_mae: 50542.4883
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50023.9414 - mae: 50023.9414 - val_loss: 50518.4492 - val_mae: 50518.4492
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49985.8477 - mae: 49985.8477 - val_loss: 50477.6211 - val_mae: 50477.6211
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49949.2578 - mae: 49949.2578 - val_loss: 50456.9922 - val_mae: 50456.9922
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49920.7422 - mae: 49920.7422 - val_loss: 50436.7852 - val_mae: 50436.7852
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49888.8633 - mae: 49888.8633 - val_loss: 50414.5000 - val_mae: 50414.5000
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49860.6484 - mae: 49860.6484 - val_loss: 50399.9688 - val_mae: 50399.9688
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49837.7422 - mae: 49837.7422 - val_loss: 50383.4922 - val_mae: 50383.4922
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49811.8125 - mae: 49811.8125 - val_loss: 50363.7852 - val_mae: 50363.7852
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49791.2070 - mae: 49791.2070 - val_loss: 50355.5234 - val_mae: 50355.5234
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49769.1875 - mae: 49769.1875 - val_loss: 50344.2891 - val_mae: 50344.2891
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49745.4141 - mae: 49745.4141 - val_loss: 50324.3867 - val_mae: 50324.3867
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49724.2461 - mae: 49724.2461 - val_loss: 50315.6328 - val_mae: 50315.6328
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49705.1211 - mae: 49705.1211 - val_loss: 50314.5977 - val_mae: 50314.5977
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49691.9922 - mae: 49691.9922 - val_loss: 50305.2305 - val_mae: 50305.2305
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49673.3359 - mae: 49673.3359 - val_loss: 50304.2930 - val_mae: 50304.2930
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49659.1602 - mae: 49659.1602 - val_loss: 50289.8477 - val_mae: 50289.8477
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49639.4453 - mae: 49639.4453 - val_loss: 50288.5664 - val_mae: 50288.5664
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49629.3125 - mae: 49629.3125 - val_loss: 50283.7812 - val_mae: 50283.7812
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49615.8320 - mae: 49615.8320 - val_loss: 50286.0078 - val_mae: 50286.0078
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49603.2695 - mae: 49603.2695 - val_loss: 50276.1055 - val_mae: 50276.1055
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49588.5781 - mae: 49588.5781 - val_loss: 50271.6602 - val_mae: 50271.6602
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49580.1445 - mae: 49580.1445 - val_loss: 50276.0508 - val_mae: 50276.0508
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49568.5586 - mae: 49568.5586 - val_loss: 50278.2930 - val_mae: 50278.2930
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49559.2969 - mae: 49559.2969 - val_loss: 50262.5391 - val_mae: 50262.5391
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49548.8203 - mae: 49548.8203 - val_loss: 50253.4883 - val_mae: 50253.4883
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49538.2383 - mae: 49538.2383 - val_loss: 50261.2266 - val_mae: 50261.2266
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49527.4531 - mae: 49527.4531 - val_loss: 50256.8164 - val_mae: 50256.8164
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49520.4219 - mae: 49520.4219 - val_loss: 50266.0273 - val_mae: 50266.0273
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49509.1172 - mae: 49509.1172 - val_loss: 50248.9141 - val_mae: 50248.9141
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49502.5547 - mae: 49502.5547 - val_loss: 50241.2617 - val_mae: 50241.2617
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49495.5625 - mae: 49495.5625 - val_loss: 50237.1836 - val_mae: 50237.1836
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49485.8203 - mae: 49485.8203 - val_loss: 50252.5273 - val_mae: 50252.5273
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49481.6172 - mae: 49481.6172 - val_loss: 50241.8398 - val_mae: 50241.8398
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49472.5703 - mae: 49472.5703 - val_loss: 50250.6211 - val_mae: 50250.6211
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49465.5117 - mae: 49465.5117 - val_loss: 50259.4727 - val_mae: 50259.4727
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49456.1133 - mae: 49456.1133 - val_loss: 50240.0508 - val_mae: 50240.0508
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49453.2812 - mae: 49453.2812 - val_loss: 50252.2695 - val_mae: 50252.2695
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49445.5742 - mae: 49445.5742 - val_loss: 50258.0586 - val_mae: 50258.0586
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49442.3711 - mae: 49442.3711 - val_loss: 50251.6641 - val_mae: 50251.6641
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49431.7930 - mae: 49431.7930 - val_loss: 50245.3359 - val_mae: 50245.3359
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49428.0586 - mae: 49428.0586 - val_loss: 50258.2109 - val_mae: 50258.2109

In [48]:
test_loss,test_mae = model.evaluate(X_test,Y_test)
print(f'Test MAE : {test_mae} , Test Loss : ${test_loss}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50237.1836 - mae: 50237.1836
Test MAE : 50237.18359375 , Test Loss : $50237.18359375

In [49]:
model.save("regression_salary.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.